# Generated by Django 6.0.1 on 2026-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_image',
            field=models.ImageField(default='posts/images/egg.png', upload_to='posts/images/'),
        ),
    ]
