# Generated by Django 6.0.1 on 2026-01-12 13:05

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_postmodel_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_image',
            field=models.ImageField(default='posts/images/egg.png', upload_to=Posts.models.generate_image_uuid),
        ),
    ]
