# Generated by Django 6.0.1 on 2026-01-12 13:05

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='egg.png', upload_to=Users.models.generate_image_uuid),
        ),
    ]
